version: "3.9"
services:
  fastapi-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/src
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
